"""Stamp the build sha on each analysis

Revision ID: 2589cc46913f
Revises: 9c8a35a018e7
Create Date: 2026-08-09 22:47:52.516036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2589cc46913f'
down_revision: Union[str, Sequence[str], None] = '9c8a35a018e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('analyses', sa.Column('app_version', sa.String(length=40), nullable=True))


def downgrade() -> None:
    op.drop_column('analyses', 'app_version')


# Autogenerate also proposed creating ix_projects_org_id and a projects.org_id foreign
# key. Both were removed by hand, and deliberately: the baseline migration already
# creates them, so any database built from this repo's migrations has them and these
# statements would fail on it. They appeared only because they were autogenerated against
# a long-lived development database that predates Alembic — it was created by
# `create_all` back when the model had neither, and was stamped at baseline on
# 2026-08-09 on the assumption that it matched. It did not, quite.
#
# The lesson is about the tool, not this column: `--autogenerate` diffs the models
# against whichever database it is pointed at, so it faithfully reports that database's
# private history as though it were a schema change. Read every generated migration
# before committing it.
