"""Billing fields on org

Revision ID: 91334c63456d
Revises: 2589cc46913f
Create Date: 2026-08-11 14:17:52.863329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91334c63456d'
down_revision: Union[str, Sequence[str], None] = '2589cc46913f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default added by hand. Autogenerate proposed both NOT NULL columns without
    # one, which cannot be added to a table that already has rows — every existing
    # organisation would have no value to put there, and Postgres refuses rather than
    # guessing. The generated version would have failed on the deployed database on its
    # first run, during a deploy, with the API container exiting on boot.
    #
    # The default is also the correct product behaviour: an organisation that predates
    # billing is on the free plan with no credits, which is exactly what these say.
    op.add_column(
        'orgs',
        sa.Column('plan', sa.String(length=20), nullable=False, server_default='free'),
    )
    op.add_column('orgs', sa.Column('billing_customer_id', sa.String(length=80), nullable=True))
    op.add_column('orgs', sa.Column('subscription_status', sa.String(length=20), nullable=True))
    op.add_column(
        'orgs',
        sa.Column('analysis_credits', sa.Integer(), nullable=False, server_default='0'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orgs', 'analysis_credits')
    op.drop_column('orgs', 'subscription_status')
    op.drop_column('orgs', 'billing_customer_id')
    op.drop_column('orgs', 'plan')
    # ### end Alembic commands ###
